version: '3.8'

services:
  web:
    image: nginx
    volumes:
      - /home/torpeda/intership-task/html:/usr/share/nginx/html:rw
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    image: php:fpm
    volumes:
      - /home/torpeda/intership-task/html:/usr/share/nginx/html:rw

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

